[dev]
  command = "yarn start"
  autoLaunch = false
  port = 8888
  targetPort = 3000

[build]
  command = "yarn build"
  publish = "dist"
  functions = "functions"

[build.environment]
  TZ="Asia/Tokyo"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["jsdom"]
  included_files = ["./assets/img/map-mobile.svg", "./assets/img/base.png", "./assets/font/Mamelon-for-ogp.otf"]



