[dev]
  command = "yarn dev"
  autoLaunch = false

[build]
  command = "npm run generate"
  publish = "dist"
  functions = ".output/server"

[build.environment]
  TZ="Asia/Tokyo"

# [functions]
#   node_bundler = "esbuild"
#   external_node_modules = ["jsdom"]
#   included_files = ["./assets/img/map-mobile.svg"]
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200


